name: video_chat_mobile
description: "A mobile wrapper for the Video Chat App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
